kind: pipeline
type: docker
name: default

steps:
  - name: build-test-image
    image: python:3-alpine
    commands:
      - pip install -r requirements.txt
      - python manage.py makemigrations posts
      - python manage.py migrate posts
      - python manage.py test
    when:
      branch: [feature-*, hotfix-*, bugfix-*]
      event: [pull-request]

#  - name: build-production-image
#    image: python:3-alpine
#    commands:
#      - pip install -r requirements.txt
#      - python manage.py makemigrations posts
#      - python manage.py migrate posts
#    when:
#      branch: [master]
#      event: [tag]

services:
  - name: db
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
