"""
Django settings for droneci_test project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from .base import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)


# Application definition

WSGI_APPLICATION = 'config.wsgi.application'
